name: Generate Apple System Status RSS Feeds

# on:
#   schedule:
#     - cron: '*/15 * * * *'   # every 15 minutes
#   workflow_dispatch:       # manual trigger

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests feedgen

      - name: Generate all RSS feeds
        run: python .github/scripts/generate_all_status_rss.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update Apple system status RSS feeds [skip ci]"
            git push
          fi
